#!/usr/bin/perl
my @args = @ARGV;
my %keywords;
for (<>) {
    for (split /\b/, $_) {
        if (/^k_([_0-9a-zA-Z]*)/) {
            $keywords{$1} = 1;
        }
    }
}

print ("/* Generated by:\n".
       "   ".(join ' ', $0, @args)."\n".
       "*/\n");
for (sort keys %keywords) {
    print "KEYWORD($_)\n";
}

